name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Match the Ruby version required for Jekyll
        bundler-cache: true

    - name: Install Dependencies
      run: bundle install

    - name: Build Site
      run: bundle exec jekyll build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: ./_site